# Generated by Django 5.1.1 on 2024-10-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('recipe', '0002_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.ingredient'),
        ),
    ]
